name: "Deploy Now: Execute Build"

on:
  workflow_call:
    inputs:
      site-url:
        required: true
        type: string
      branch-id:
        required: true
        type: string

env:
  DEPLOYMENT_FOLDER: dist

jobs:
  build-project:
    name: build js-website
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build static website
        run: npm run build

      - name: Verify deployment content
        run: |
          test -f dist/index.html
          test -f dist/impressum.html
          test -f dist/datenschutz.html

      - name: Store deployment content
        uses: ionos-deploy-now/artifact-action@v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          service-host: api-eu.ionos.space
          project-id: a077c71b-5183-475e-b2d7-7152c966bd6a
          branch-id: ${{ inputs.branch-id }}
          version: ${{ github.sha }}
          folder: ${{ env.DEPLOYMENT_FOLDER }}
          config-file: .deploy-now/js-website/config.yaml
          action: upload
